### ISSUE TITLE
Does not compile with nim 0.13.0

### ISSUE THREAD

**Issue by xyproto** [nim-lang/nimble#203]
nimble (both latest release tag and latest on the master branch) does not compile with nim 0.13.0.

I'm on 64-bit Arch Linux.
nim 0.13.0
git 2.7.0

---

When performing these commands:

```
git clone git://github.com/nimrod-code/nimble.git 0.7.0
cd nimble/src
nim c -d:release nimble.nim
```

The output is:

```
nimblepkg/nimscriptsupport.nim(8, 11) Error: cannot open 'compiler/ast'
```

---

When performing these commands:

```
git clone https://github.com/nim-lang/nimble.git
cd nimble
git clone -b v0.13.0 --depth 1 https://github.com/nim-lang/nim vendor/nim
nim c -r src/nimble install
```

The output is:

```
Traceback (most recent call last)
nimble.nim(962)          nimble
nimble.nim(887)          doAction
nimble.nim(869)          execHook
packageparser.nim(230)   readPackageInfo
Error: unhandled exception: Could not read package info file in /home/alexander/checkout/nimble/nimble.nimble;
  Reading as ini file failed with: 
    Invalid section: .
  Evaluating as NimScript file failed with: 
    Error: cannot open '/home/alexander/checkout/nimble/lib/system.nim'. [NimbleError]
Error: execution of an external program failed: '/home/alexander/checkout/nimble/src/nimble install'
```

**Comment by dom96** [comment]
Where does your Nim installation reside?

I'm guessing ``/usr/bin/nim`` and ``/usr/local/lib/nim``?

**Comment by xyproto** [comment]
Yes, `/usr/bin/nim`, but not `/usr/local/lib/nim`.

**Comment by jiyinyiyong** [comment]
@dom96 yes, and I installed Nim with Homebrew on OS X

```
=>> which nim
/usr/local/bin/nim
=>> brew info nim
nim: stable 0.13.0 (bottled), HEAD
Statically typed, imperative programming language
http://nim-lang.org/
/usr/local/Cellar/nim/0.12.0 (197 files, 4.8M)
  Poured from bottle
/usr/local/Cellar/nim/0.13.0 (202 files, 4.8M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nim.rb
==> Dependencies
Build: xz ✔
```

**Comment by davidpelaez** [comment]
This is because Nim cannot find the path. Uninstall nim, then you can do `brew edit nim` and put this in the file:

```
class Nim < Formula
  desc "Statically typed, imperative programming language"
  homepage "http://nim-lang.org/"
  version "0.13"
  url "http://nim-lang.org/download/nim-0.13.0.tar.xz"
  sha256 "cd61f5e5768d4063596d6df578ae9bb5f9d52430773542987e91050b848cb1a9"
  head "https://github.com/Araq/Nim.git", :branch => "devel"

  bottle do
    cellar :any_skip_relocation
    sha256 "1a5c730b9a13b095a1ffbab95079ecd5c1c04a0fe01c1ee53289ac73af905b6a" => :el_capitan
    sha256 "e707da286aeadd48b85b9021f16c3b9831850f8806e297c1e40df2b68c777e20" => :yosemite
    sha256 "70c7a262d12c1ae48185061131794aa257726846c808e0d388a0fd3d8f416dc6" => :mavericks
  end

  def install
    if build.head?
      system "/bin/sh", "bootstrap.sh"
    else
      system "/bin/sh", "build.sh"
    end
    system "/bin/sh", "install.sh", prefix

    # Nim doesn't look for a config file in /usr/local, hence we need to make
    # sure to always pass the exact location of the path

    wrapping_script = bin + "nim"

    wrapping_script.write <<-EOS.undent
      #!/bin/bash

      # Actual path of the nim compiler
      nim="#{prefix}/nim/bin/nim"

      if [ -z "$1" ]; then
        # There were no args
        exec "$nim"
      else
        # Take the first arg, the command and then append the path
        command="$1"
        shift
        exec "$nim" $command --path:"#{prefix}/nim/lib" $@
      fi
    EOS

    wrapping_script.chmod 0755

    # Alias nimrod to the nim wrapping script
    bin.install_symlink wrapping_script => "nimrod"
  end

  test do
    (testpath/"hello.nim").write <<-EOS.undent
      echo("hello")
    EOS
    assert_equal "hello", shell_output("#{bin}/nim compile --verbosity:0 --run #{testpath}/hello.nim").chomp
  end
end

```

That should solve a part of the bug. I'm currently trying to solve how to install Nimble after using the updated recipe that includes the compile's path. If you find a way please me know. Hope this helps to move you forward.

**Comment by davidpelaez** [comment]
@xyproto did my last comment helped solve the issue?

**Comment by dom96** [comment]
@davidpelaez what is different about your brew file?

**Comment by dom96** [comment]
Also, I think @xyproto is using Arch Linux. No ``brew`` there.

**Comment by davidpelaez** [comment]
@dom96 it has a wrapper script that always points to the proper path. I just opened a PR on Homebrew https://github.com/Homebrew/homebrew/pull/48446

My bad, I meant @jiyinyiyong who mentioned he was using brew. In @xyproto the wrapping script with the proper paths could solve the part of the issue where he's seeing this error: `Error: cannot open '/home/alexander/checkout/nimble/lib/system.nim'. [NimbleError]`.

That error is because the path isn't properly resolved. The wrapping script makes sure to always add an explicit `--path` call to every nim command.

**Comment by xyproto** [comment]
I am also maintaining nim for Arch Linux. I think it would be better if the nim upstream developers fixed the issue (if this really is the issue), rather than patching and adding wrapper scripts that add `--path`.

**Comment by tylereaves** [comment]
Running in to this also.... @davidpelaez's script change doesn't help.

```
Hint:  [Link]
Hint: operation successful (92975 lines compiled; 3.164 sec total; 334.342MB; Debug Build) [SuccessX]
Traceback (most recent call last)
nimble.nim(962)          nimble
nimble.nim(887)          doAction
nimble.nim(869)          execHook
packageparser.nim(230)   readPackageInfo
Error: unhandled exception: Could not read package info file in /Users/tyler/discogs/nimble/nimble.nimble;
  Reading as ini file failed with:
    Invalid section: .
  Evaluating as NimScript file failed with:
    Error: cannot open '/Users/tyler/discogs/nimble/lib/system.nim'. [NimbleError]
Error: execution of an external program failed: '/Users/tyler/discogs/nimble/src/nimble install'```

**Comment by davidpelaez** [comment]
@xyproto there's a suggestion to use env vars. But I don't have the exact link here, but I think it shouldn't be hard to get this solved by next week in a small PR.

@tylereaves what version do you have of Nim? You installed with brew, right? Where did you put the script. I have tested it and it works on my mac and on two of my coworkers. Are you certain you are running the script? I suspect your issue could be that the path hierarchy of your system resolved first to the nim binary link installed by brew instead of the wrapper script that you maybe places in /usr/bin or similar? Just trying to find out what went wrong and how to help you

**Comment by davidpelaez** [comment]
@tylereaves BTW, my script will not make nimble compile. I haven't got to solve that yeat, however the path related error about not finding `system.nim` should disappear hence letting your focus in the other parts of the problem.

**Comment by mirek** [comment]
Unfortunately this is a show stopper, is there a workaround to compile nimble on OSX?

**Comment by dom96** [comment]
@mirek Don't install Nimble via brew, clone the Nim repo, bootstrap manually and add Nim's ``bin`` path to your OS PATH: https://github.com/nim-lang/Nim#compiling. (**Do not use ``install.sh`` or ``./koch install``)

**Comment by mirek** [comment]
Thanks @dom96 your suggestion does work for me as a workaround.

```
brew uninstall nim

cd ~/
git clone https://github.com/nim-lang/Nim.git
cd Nim
git clone --depth 1 https://github.com/nim-lang/csources
cd csources && sh build.sh
export PATH=~/Nim/bin:$PATH

# nim --version
# nimble install lmdb
# ...works fine.
```

**Comment by sheerun** [comment]
The same issue for me. Why not install nim via homebrew?

**Comment by bobgus** [comment]
I was able to get nim and nimble and aporia to run on Fedora 23.

Unfortunately, I did not document my steps well enough to be positive.

I did have to load some additional libraries - gtkviewsource2 was one of them.

===

I also spent some time with homebrew (my preferred package loader) on a Macbook Air running 10.11.3
Nim 0.13.0 installs fine (in /usr/local.. ), but nimble does not have a brew formula as yet and my attempts at moving the nimble source around to get the directories to match were not successful yet.

I will try some of your hints if I have time today

**Comment by dom96** [comment]
@sheerun Because Nimble needs to be able to find the Nim standard library for NimScript support. Unfortunately when Nim is installed by Homebrew into ``/usr/bin`` and ``/usr/lib/nim`` (or wherever it installs it to) then Nimble has trouble finding the standard library.

**Comment by sheerun** [comment]
Can homebrew installer be fixed?

**Comment by dom96** [comment]
Don't think so. Patches to Nimble (and possibly also Nim) are needed.

**Comment by bobgus** [comment]
Do you have an idea as to the nature of these patches?

**Comment by xyproto** [comment]
Could an environment variable like ´NIM_HOME´ be introduced and be used by both nim and nimble? Would that work? Several other programming languages have a similar approach.

**Comment by dom96** [comment]
Nah. The Nim compiler should be able to figure it out. Having the user set it explicitly is annoying and adds a barrier to entry which I personally dislike.

**Comment by xyproto** [comment]
For the case of Arch Linux, the environment variable would be set for the entire system, in /etc/profile.d and/or a script for running nim. The user would not have to explicitly set it. It can be hard for a compiler to figure out where the library files are, unless it looks at an environment variable, has a configuration file or checks a list of possible paths (or a combination of all three).

**Comment by Araq** [comment]
> unless it looks at an environment variable, has a configuration file or checks a list of possible paths (or a combination of all three).

The compiler has a configuration file!

**Comment by xyproto** [comment]
@Araq, so the solution to 'compiler/ast' not being find should be to set the library path in /etc/nim.cfg?

**Comment by avsej** [comment]
The way how I fixed it for my [fedora packages](https://copr.fedorainfracloud.org/coprs/avsej/nim-devel/) is to build and ship nimble in the same package as nim itself.

According to `install_nimble.nims` all you need is to compile the `nimble` binary, put it to the same directory as `nim` and copy `nimblepkg` contents to you library path. I did this in rpmspec, and this is enough to produce binary package with working nim and nimble.

I believe same approach could be implemented for homebrew

**Comment by xyproto** [comment]
No longer an issue for Arch Linux when using nimble commit 670bcec.
A new release tag would be nice, though.

**Comment by dom96** [comment]
@xyproto hrm, so that works now? How come it didn't work when you created the issue?

**Comment by kamilchm** [comment]
:+1: for new relase tag. People lose their time trying to build 0.7.0 again and again :(

**Comment by xyproto** [comment]
@dom96 The issue was created for the latest release version of nimble, not for a random commit. However, after some testing, I figured out that it worked for that specific commit, which has not yet made its way to a release. Bugs are normally reported per release, not per commit...

**Comment by dom96** [comment]
In your original post (https://github.com/nim-lang/nimble/issues/203#issue-128347818), you wrote:

> When performing these commands:

> ```
> git clone https://github.com/nim-lang/nimble.git
> cd nimble
> git clone -b v0.13.0 --depth 1 https://github.com/nim-lang/nim vendor/nim
> nim c -r src/nimble install
> ```

> The output is: ...

The first command (``git clone https://github.com/nim-lang/nimble.git``) would clone the latest commit not the latest version. 

> Bugs are normally reported per release, not per commit...

I disagree with this. You should always test the latest commit. Many bugs in the Nim repo are closed because they exist in the latest version but have been fixed in the latest commit.

**Comment by xyproto** [comment]
Why argue? Just tag a new release.

A build process that doesn't need to clone the nim repo would also be something.

**Comment by dom96** [comment]
Done https://github.com/nim-lang/nimble/releases/tag/v0.7.2

**Comment by xyproto** [comment]
Thank you. Updated the nimble package in Arch Linux to use the new release tag. It should appear in [community] shortly. And thanks for your work on nimble.

**Comment by wicast** [comment]
@xyproto nimble is still not working on archlinux,it always failed whit this message:
```  
Reading as ini file failed with: 
    Invalid section: .
  Evaluating as NimScript file failed with: 
    Cannot find nimscriptapi.nim.
```
Because the package didn't contained this file.

This is the same problem when I trying to packing nake.
Related issues:https://github.com/nim-lang/Nim/issues/3671,
https://github.com/nim-lang/nimble/issues/80

**Comment by xyproto** [comment]
@wicast, please report this issue with the Arch Linux nimble package at https://bugs.archlinux.org/. It makes it easier to keep track of the issue over time. Thanks.

**Comment by mikehcox** [comment]
I'm new to nim and not sure where to post my issues with install.  The discussion on this issue seemed closest to the problems I was having.

I was having similar issues trying to build nim 0.13.0 following the directions for installation for Linux on Fedora 23.  I was installing in my own tool directory structure, e.g. under $TOOL_ROOT where $TOOL_ROOT is pointing to the prefix dir containing a bin, lib, etc.  When the installation script detects nim is not being installed into /usr or /usr/local, it installs it into a directory named nim under the install prefix dir specified, e.g. $TOOL_ROOT/nim.  The directory has the the bin, lib, config, and doc dirs, but doc is empty and lib does not have the compiler directory under it.  Once I copied the doc and compiler directories from the checked out nim repository to the $TOOL_ROOT/nim directory, everything, including the nimble build and install worked.  I think the build/install scripts are missing some recursive directory copies.

**Comment by dom96** [comment]
@mikehcox thank you, that will help us fix this :)

**Comment by brennebeck** [comment]
Just for future reference for homebrew users: rather than `brew edit vim` as @davidpelaez suggests, I just symlinked the nim lib folder to where it's expected:
 `ln -s /usr/local/opt/nim/nim/lib /usr/local/lib/nim`

**Comment by dom96** [comment]
@brennebeck that shouldn't be necessary anymore with latest Nim and Nimble.
Is it still an issue?

**Comment by brennebeck** [comment]
Ah, brew is still building `v0.13.0`. Let me try updating the brewfile and try again :+1:

**Comment by k0pernicus** [comment]
Hi there - still an error installing Nimble (from source) after installing Nim from Homebrew (`v0.14.0`):
```
FAILURE: Could not read package info file in /Users/antonin/nimble/nimble.nimble;
  Reading as ini file failed with:
    Invalid section: .
  Evaluating as NimScript file failed with:
    Error: cannot open '/usr/local/lib/nim/system.nim'.
```

This symlink seems working: `ln -s /usr/local/Cellar/nim/0.14.0/nim/lib/system.nim /usr/local/lib/nim/system.nim`

**Comment by Sembei** [comment]
same issue as @k0pernicus on os x 10.10.5 and Nim (0.14.2) from Hombrew. Symlinking is not working for me

**Comment by Immortalin** [comment]
Same issue here

**Comment by dom96** [comment]
Hopefully this isn't an issue anymore. Especially now that Nimble is bundled with Nim. Closing for now, but please let me know if you have similar issues and I will reopen and investigate.
