### ISSUE TITLE
Do not swallow compiler output

### ISSUE THREAD

**Issue by endragor** [nim-lang/nimble#382]
I'd like to see the progress going when my project is being built, and I also like to see the compilation stats (memory, time) Nim outputs when it finishes. But nimble swallows all of that and just silently exits when build process is complete.
It was fine before the fancy coloring was added to nimble output. So for some reason a useful feature was replaced with cosmetics at that point.

**Comment by dom96** [comment]
I believe this has been fixed in HEAD.

**Comment by dom96** [comment]
Can you verify?

**Comment by endragor** [comment]
Still gets swallowed for me at ebf4eace3929464dba59ea21e0f9f584760fa2cf

**Comment by dom96** [comment]
For what command does this occur? ``nimble build``?

**Comment by endragor** [comment]
Yes.

**Comment by dom96** [comment]
``nimble build`` swallows output by-design. I think you should be able get it via ``--debug`` or ``--verbose``.

**Comment by genotrance** [comment]
This is being improved somewhat - Nimble will show `--hints:off` output for all Nim commands by default. This is almost silent on devel. If the --verbose flag is specified, the command line will be displayed and regular Nim output. See #828.
